language: go

go:
  - 1.13.x
  - 1.14.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

addons:
  postgresql: "9.4"

env:
  - DBNAME=kallax_test DBUSER=postgres DBPASS='' GOPATH=/tmp/whatever:$GOPATH

services:
  - postgresql

before_script:
  - psql -c 'create database kallax_test;' -U postgres

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
